
DROP TABLE IF EXISTS keys;
CREATE TABLE keys (id SERIAL NOT NULL, keyname CHARACTER VARYING(20), key CHARACTER VARYING(100), PRIMARY KEY (id), CONSTRAINT key_constraint UNIQUE (keyname));
DROP TABLE IF EXISTS login_history;
CREATE TABLE login_history (id SERIAL NOT NULL, username_en BYTEA, machine CHARACTER VARYING(100), ip4_addr CHARACTER VARYING(20), login_time TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id));
DROP TABLE IF EXISTS users;
CREATE TABLE users (id SERIAL NOT NULL, username_en BYTEA NOT NULL, password_en BYTEA NOT NULL, role CHARACTER VARYING(20) NOT NULL, PRIMARY KEY (id), CONSTRAINT username_uq UNIQUE (username_en));
